allowBuilds:
  core-js: true
  cpu-features: true
  esbuild: true
  msw: true
  protobufjs: true
  ssh2: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  '@voidzero-dev/vite-plus-test': latest
  '@voidzero-dev/vite-plus-core': latest
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
